services:
  backend:
    build:
      context: ./backend
    environment:
      - ASPNETCORE_URLS=http://+:7400
    ports:
      - "7400:7400"

  frontend:
    build:
      context: ./frontend
    ports:
      - "7180:7180"
    depends_on:
      - backend
