services:
  backend:
    build:
      context: ./backend
    environment:
      - ASPNETCORE_URLS=http://+:4000
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
